// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Models;

namespace Project2.Migrations
{
    [DbContext(typeof(ScheduleApplicationContext))]
    [Migration("20220328015351_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project2.Models.DateTime", b =>
                {
                    b.Property<int>("DateTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("DateTimeId");

                    b.ToTable("DateTime");

                    b.HasData(
                        new
                        {
                            DateTimeId = 1,
                            StartDate = "03/21/2022",
                            StartTime = "8 AM"
                        },
                        new
                        {
                            DateTimeId = 2,
                            StartDate = "03/21/2022",
                            StartTime = "9 AM"
                        },
                        new
                        {
                            DateTimeId = 3,
                            StartDate = "03/21/2022",
                            StartTime = "10 AM"
                        },
                        new
                        {
                            DateTimeId = 4,
                            StartDate = "03/21/2022",
                            StartTime = "11 AM"
                        },
                        new
                        {
                            DateTimeId = 5,
                            StartDate = "03/21/2022",
                            StartTime = "12 AM"
                        },
                        new
                        {
                            DateTimeId = 6,
                            StartDate = "03/21/2022",
                            StartTime = "1 PM"
                        },
                        new
                        {
                            DateTimeId = 7,
                            StartDate = "03/21/2022",
                            StartTime = "2 PM"
                        },
                        new
                        {
                            DateTimeId = 8,
                            StartDate = "03/21/2022",
                            StartTime = "3 PM"
                        },
                        new
                        {
                            DateTimeId = 9,
                            StartDate = "03/21/2022",
                            StartTime = "4 PM"
                        },
                        new
                        {
                            DateTimeId = 10,
                            StartDate = "03/21/2022",
                            StartTime = "5 PM"
                        },
                        new
                        {
                            DateTimeId = 11,
                            StartDate = "03/21/2022",
                            StartTime = "6 PM"
                        },
                        new
                        {
                            DateTimeId = 12,
                            StartDate = "03/21/2022",
                            StartTime = "7 PM"
                        },
                        new
                        {
                            DateTimeId = 13,
                            StartDate = "03/21/2022",
                            StartTime = "8 PM"
                        },
                        new
                        {
                            DateTimeId = 14,
                            StartDate = "03/22/2022",
                            StartTime = "8 AM"
                        },
                        new
                        {
                            DateTimeId = 15,
                            StartDate = "03/22/2022",
                            StartTime = "9 AM"
                        },
                        new
                        {
                            DateTimeId = 16,
                            StartDate = "03/22/2022",
                            StartTime = "10 AM"
                        },
                        new
                        {
                            DateTimeId = 17,
                            StartDate = "03/22/2022",
                            StartTime = "11 AM"
                        },
                        new
                        {
                            DateTimeId = 18,
                            StartDate = "03/22/2022",
                            StartTime = "12 AM"
                        },
                        new
                        {
                            DateTimeId = 19,
                            StartDate = "03/22/2022",
                            StartTime = "1 PM"
                        },
                        new
                        {
                            DateTimeId = 20,
                            StartDate = "03/22/2022",
                            StartTime = "2 PM"
                        },
                        new
                        {
                            DateTimeId = 21,
                            StartDate = "03/22/2022",
                            StartTime = "3 PM"
                        },
                        new
                        {
                            DateTimeId = 22,
                            StartDate = "03/22/2022",
                            StartTime = "4 PM"
                        },
                        new
                        {
                            DateTimeId = 23,
                            StartDate = "03/22/2022",
                            StartTime = "5 PM"
                        },
                        new
                        {
                            DateTimeId = 24,
                            StartDate = "03/22/2022",
                            StartTime = "6 PM"
                        },
                        new
                        {
                            DateTimeId = 25,
                            StartDate = "03/22/2022",
                            StartTime = "7 PM"
                        },
                        new
                        {
                            DateTimeId = 26,
                            StartDate = "03/22/2022",
                            StartTime = "8 PM"
                        },
                        new
                        {
                            DateTimeId = 27,
                            StartDate = "03/23/2022",
                            StartTime = "8 AM"
                        },
                        new
                        {
                            DateTimeId = 28,
                            StartDate = "03/23/2022",
                            StartTime = "9 AM"
                        },
                        new
                        {
                            DateTimeId = 29,
                            StartDate = "03/23/2022",
                            StartTime = "10 AM"
                        },
                        new
                        {
                            DateTimeId = 30,
                            StartDate = "03/23/2022",
                            StartTime = "11 AM"
                        },
                        new
                        {
                            DateTimeId = 31,
                            StartDate = "03/23/2022",
                            StartTime = "12 AM"
                        },
                        new
                        {
                            DateTimeId = 32,
                            StartDate = "03/23/2022",
                            StartTime = "1 PM"
                        },
                        new
                        {
                            DateTimeId = 33,
                            StartDate = "03/23/2022",
                            StartTime = "2 PM"
                        },
                        new
                        {
                            DateTimeId = 34,
                            StartDate = "03/23/2022",
                            StartTime = "3 PM"
                        },
                        new
                        {
                            DateTimeId = 35,
                            StartDate = "03/23/2022",
                            StartTime = "4 PM"
                        },
                        new
                        {
                            DateTimeId = 36,
                            StartDate = "03/23/2022",
                            StartTime = "5 PM"
                        },
                        new
                        {
                            DateTimeId = 37,
                            StartDate = "03/23/2022",
                            StartTime = "6 PM"
                        },
                        new
                        {
                            DateTimeId = 38,
                            StartDate = "03/23/2022",
                            StartTime = "7 PM"
                        },
                        new
                        {
                            DateTimeId = 39,
                            StartDate = "03/23/2022",
                            StartTime = "8 PM"
                        });
                });

            modelBuilder.Entity("Project2.Models.Schedules", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DateTimeId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            DateTimeId = 1,
                            GroupEmail = "123@gmail.com",
                            GroupName = "Sheng Lei",
                            GroupPhone = "123-123-1234",
                            GroupSize = 4
                        });
                });

            modelBuilder.Entity("Project2.Models.Schedules", b =>
                {
                    b.HasOne("Project2.Models.DateTime", "DateTime")
                        .WithMany()
                        .HasForeignKey("DateTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
